<?php

function popular_news_front_theme ( $existing, $type, $theme, $path ) {
    return [
        'popular_news_front' => array(
            'template'  => 'popular_news_front',
            'variables' => [
                'content'  => [],
            ],
        ),
//        'popular_news_second_front' => array(
//            'template'  => 'popular_news_front',
//            'variables' => [
//                'content'  => [],
//            ],
//        ),
    ];
}